services:
        # Указываем произвольное название сервиса
        prometheus:
                # Указываем название папки с Dockerfile
                build: prom
                # Пробрасываем порты, чтобы можно было получать данные из контейнера, обращаясь к айпи хоста
                ports:
                        - 9090:9090
                # Эта строчка указывает докеру не создавать сеть, а использовать хостовый brige интерфейс
                network_mode: bridge
        grafana:
                build: grafana
                ports:
                        - 3000:3000
                network_mode: bridge
