apiVersion: 1

datasources:
        - name: Prometheus
          type: prometheus
          # Адрес для сбора метрик указываем хоста, на этом порту отдаёт данные prometeus (порт пробрасывается при запуске контейнера в файле docker_compose.yml)
          url: 'http://10.11.12.1:9090'
